#! /bin/sh
# Philips DPMMount daemon startup script
#
PATH=/usr/bin:/usr/local/bin
DAEMON=/usr/local/bin/DPMMountd
NAME=DPMMountd
DESC="Philips DPM handler daemon"
PARAMS="-m 2 -l /tmp/PhilipsDPM"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo "Starting Philips DPM Handeler"
	/sbin/start-stop-daemon --background --start --quiet --exec $DAEMON -- $PARAMS
	;;
  stop)
  	echo "Stopping Philips DPM Handeler"
	/sbin/start-stop-daemon --stop --quiet --exec $DAEMON
	;;
  *)
	echo "Usage: /etc/init.d/$NAME {start|stop}" >&2
	exit 1
	;;
esac

exit 0
